// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uftkbzvrapcfxdlpcxpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdGtienZyYXBjZnhkbHBjeHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzI5NjYsImV4cCI6MjA3MDE0ODk2Nn0.xxNgdYhMVaePe3D7Xj-wgILvSRaPawDgFaPP-xAszPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});